services:
  db:
    image: postgres:15
    container_name: biblioteca_db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: biblioteca_app
    environment:
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: app123
      DB_NAME: library
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: